### ISSUE TITLE
刷新课程功能废了（wxb程序员开始动手了？？？）

### ISSUE THREAD

**Issue by 1357310795** [yuhuison/WXBThirdLogin#4]
![QQ截图20200312182651](https://user-images.githubusercontent.com/35869804/76512068-109c4880-648f-11ea-9cbf-e09e51572882.png)
电脑时间是准确的。这个功能明明下午还能用的……

**Comment by yuhuison** [comment]
有一个函数叫GetTime 用来取时间戳的，把后面那个时间改成 1970年1月1日8时（原来是1970年1月1日0时）

**Comment by yuhuison** [comment]
就是salt对应那个

**Comment by 1357310795** [comment]
> 就是salt对应那个

看到了。谢谢提示
