### ISSUE TITLE
有没有办法让无限宝禁止获取焦点

### ISSUE THREAD

**Issue by 1357310795** [yuhuison/WXBThirdLogin#7]
测试发现，那个强力解除锁屏仅仅是setparent……
有没有办法让无限宝禁止获取焦点？
还有能不能加个菜单或热键把无限宝窗口释放出来？

**Comment by yuhuison** [comment]
DLL注入HOOK
SetFocus 和  SetForegroundWindow可以实现
不DLL注入的话，我只能想到用时钟，每100毫秒获取并储存当前的激活窗口(GetForegroundWindow)
如果下次检测时发现当前窗口变成了无限宝，就取消无限宝的激活并且激活上一次的窗口
